### ISSUE TITLE
Need to update dependencies

### ISSUE THREAD

**Issue by stevenpersia** [stevenpersia/tinder-react-native#13]
There are some potential security vulnerabilities in dependencies. Need to update dependencies and test app.

**Comment by mecm1993** [comment]
I would like to work on this issue.

**Comment by stevenpersia** [comment]
I'm sorry someone just make a pull request ! Thank you for your help ;)

**Comment by cocoliliace** [comment]
You're welcome. Glad to help :)

**Comment by stevenpersia** [comment]
Thank you @ChingChang9
