### ISSUE TITLE
I'nt to contribute in application.

### ISSUE THREAD

**Issue by kukokp** [stevenpersia/tinder-react-native#18]
Hello sir,
I made some changes in application, resolved tab swipe issue & provide the Android X support with react-native 0.60.3 , so please give me the permission to update the code.

Thanks
kukokp

**Comment by stevenpersia** [comment]
Hi @kukokp !
Create a pull request and I will check it ;)

Thank you for your participation.

**Comment by kukokp** [comment]
@stevenpersia 
I tried I got permission related error.
$ git push origin master                                                                                                       
remote: Permission to stevenpersia/tinder-react-native.git denied to kukokp.                                                   
fatal: unable to access 'https://github.com/stevenpersia/tinder-react-native.git/': The requested URL returned error: 403      )

**Comment by stevenpersia** [comment]
That's weird. I don't need to give you permission. I think you did something wrong with PR process.
You can follow this documentation : https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github
