### ISSUE TITLE
Cant run project

### ISSUE THREAD

**Issue by reginaldojunior** [stevenpersia/tinder-react-native#19]
I follow instructions of readme but project is not running.

When execute command `react-native run-android` return this error:

![Captura de tela de 2019-12-03 19-35-59](https://user-images.githubusercontent.com/7466894/70095689-2b476180-1604-11ea-84ec-c6a53cc7c445.png)

PS: Sorry my bad english :smile:

**Comment by yhailu** [comment]
I believe in the docs the authors wrote something about not running in android as they only worked on the ios version.

**Comment by reginaldojunior** [comment]
Yeah, i build an version to work in android :smile: 

https://github.com/reginaldojunior/afrotinder/tree/story/get-location
