### ISSUE TITLE
React Native Web

### ISSUE THREAD

**Issue by VikashKothary** [stevenpersia/tinder-react-native#20]
Hey, I was having a look at your app. It looks very cooo and I'm looking forward to getting it running. 

Quick question. Have you considered using React Native for Web? I'm not very familiar with it but I think it would be cool if it also worked as a Web App.

Love to get your perspective.

**Comment by kopax** [comment]
I am currently building one with `react-native-web` and it can be straightforward. Some features can be just for mobile so it needs to be disactivated when on web, then the rest should do it automatically.

I am looking for a project react-native with a swipe such as within the gmail android app. swipe left store, swipe right add to favorite. Do you guy have anything to recommend me?

**Comment by stevenpersia** [comment]
Hi @VikashKothary ! Sorry for my late answer. I was very busy last month.

To answer your question, I'm very interested in making a React Native Web version, but unfortunately I don't have the time even if it shouldn't be too long.

It seems that @kopax  is working on it.

@kopax , unfortunately, I have nothing to recommend to you.

**Comment by kopax** [comment]
Hi camarade @stevenpersia , what I was looking for is more a list like the android gmail app, I am not sure if this would be a good starting point, otherwise I would do it. This is for example closer to what I want: https://github.com/jemise111/react-native-swipe-list-view .

**Comment by stevenpersia** [comment]
I did a quick search and surprisingly, I can't find anything close to it! Except the repo you just shared who seems to suit your needs. 

It can be interesting to make your own. If you do, I will follow this very closely!

**Comment by stevenpersia** [comment]
If you guys are agree, I will close this PR. You can ask to reopen it if you want.
