### ISSUE TITLE
Android formatting is completely out.

### ISSUE THREAD

**Issue by alimsyed** [stevenpersia/tinder-react-native#21]
On android 9 I have this problem that I can't get rid of. 
The formatting is completely off. 
![Screenshot_20200223_022530](https://user-images.githubusercontent.com/8600076/75101879-1c10f800-55e4-11ea-87d7-46af8520e57b.jpg)

**Comment by stevenpersia** [comment]
Sorry for my late response. As indicated on the readme, this project is currently only supported on iOS. If you have found a solution, do not hesitate to make a pull request.
