### ISSUE TITLE
I get errors when I "pod init" in the ios folder. 

### ISSUE THREAD

**Issue by craftfortress** [stevenpersia/tinder-react-native#25]
I also have a 'React' missing error message in the build scheme.

**Comment by craftfortress** [comment]
And the following errors on pod install : [!] The target `tinderReact-tvOSTests` is declared multiple times.

**Comment by navi-d97** [comment]
> And the following errors on pod install : [!] The target `tinderReact-tvOSTests` is declared multiple times.

Just open podfile and remove tvOSTargets from it.

**Comment by craftfortress** [comment]
I had to make a few more fixes but it works now thanks

**Comment by navi-d97** [comment]
> I had to make a few more fixes but it works now thanks

So where is my 10$ 😉

**Comment by craftfortress** [comment]
Its coming! I would make a pull request but I believe the changes I had to make were due to my environment. Thanks for an excellent repo, the app looks fine.
