### ISSUE TITLE
Application is not working

### ISSUE THREAD

**Issue by wasiqaftab** [stevenpersia/tinder-react-native#27]
HI

First of all this code is amazing this is exactly what i need. But when i try to run it locally its carshed 

`e/tinder-react-native/node_modules/react-native-gesture-handler/ios/RNGestureHandlerManager.m:8:9: fatal error: 'React/RCTRootContentView.h' file not found
#import <React/RCTRootContentView.h>`

this just one example.

i delete packages lock file and do npm install and again got the same error any help please

**Comment by DarkSatyr** [comment]
try `npm update --force`
