### ISSUE TITLE
Android not working

### ISSUE THREAD

**Issue by Erim32** [stevenpersia/tinder-react-native#4]
Android running issue: 
**$ react-native run-android**
![image](https://user-images.githubusercontent.com/8769532/60049533-c4c22d00-96ce-11e9-84a7-1440b79fbbed.png)

Test with win10

**Comment by stevenpersia** [comment]
As explained in `README.md`, I develop this app for iOS and for now, zero test has been done on android version. Feel free to pull request an android version if you want ;)

At the moment, my priority is to maintain a stable version in iOS and when I've got more time, do same on android.

**Comment by stevenpersia** [comment]
I close this issue for now :)

**Comment by jackregnart** [comment]
FYI, @Erim32 resolved this [in this commit](https://github.com/jackregnart/tinder-react-native/commit/b7f81d0f72cb574397afb125f00be7685d78885a) if you're still trying to get this working.

**Comment by stevenpersia** [comment]
For information, the android version works now. However, the UI has serious problems because I have only worked on iOS version.

PR #9.
