### ISSUE TITLE
Hi, amazing work here mate  is there any chance that we can check the firestore schema (structure), I would like to have a look at the way you structure firestore collections.  are you using cloud functions to propagate any data changes?  I am trying to find solutions for some scenarios for example: where we need to update older tweets when the user changes their profile picture. I believe that this is still an active issue with Fwitter.  you might want to check this out, this project provides solid solutions to such scenarios.

### ISSUE THREAD

**Issue by HoracioLopezCarvajal** [stevenpersia/tinder-react-native#43]
Hi, amazing work here mate

is there any chance that we can check the firestore schema (structure), I would like to have a look at the way you structure firestore collections.

are you using cloud functions to propagate any data changes?

I am trying to find solutions for some scenarios for example:
where we need to update older tweets when the user changes their profile picture. I believe that this is still an active issue with Fwitter.

you might want to check this out, this project provides solid solutions to such scenarios.

**Comment by neelsomani** [comment]
What makes you think there's any backend?
