### ISSUE TITLE
Build failed on iOS

### ISSUE THREAD

**Issue by stevenpersia** [stevenpersia/tinder-react-native#5]
Following the latest package updates, there is a problem when you want to build on iOS. I am working on it. If anyone finds a solution before me, do not hesitate to manifest it :)

`linker command failed with exit code 1`

**Comment by hasanmumin** [comment]
I have different error:
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening tinderReact.xcodeproj

**Comment by Sbphillips19** [comment]
I fixed this issue by adding :

`JavaScriptCore.framework` to "Link Binary With Libraries"`

Looking forward to trying out this library :)

**Comment by hasanmumin** [comment]
@Sbphillips19 can you explain more ?

**Comment by hasanmumin** [comment]
@stevenpersia Thank you. Fixed.

**Comment by stevenpersia** [comment]
Thank you @Sbphillips19 for your contribution !
I try your solution and do a pull request this week end.

**Comment by stevenpersia** [comment]
Good job @Sbphillips19 and thank you for your help. I appreciate.

**Comment by stevenpersia** [comment]
@all-contributors please add @Sbphillips19 for question
