### ISSUE TITLE
Unable to run it

### ISSUE THREAD

**Issue by GodwinEbikwo** [stevenpersia/tinder-react-native#8]
I tried running the code after cloning it, but I am unable to do so.  Please any assistance would be of great help

**Comment by GodwinEbikwo** [comment]
after I input this command "react-native run-ios" it says command not found

**Comment by stevenpersia** [comment]
Hi @GodwinEbikwo,

It seems like you don't have any dependencies installed on your development operating system.

Be sure to follow all these steps (in **React Native CLI Quickstart** tab) : https://facebook.github.io/react-native/docs/getting-started
